name: Build Frontend

on:
  push:
    paths:
      - 'Front/**'
  pull_request:
    paths:
      - 'Front/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install & Build
        run: |
          cd Front
          npm install
          npm run build
