name: Check IA

on:
  push:
    paths:
      - 'IA/**'
  pull_request:
    paths:
      - 'IA/**'

jobs:
  python-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies (IA)
        run: |
          cd IA
          pip install -r requirements.txt
          pip install pytest

      - name: Test IA
        run: |
          cd IA
          pytest
