name: Full CI Check

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  full:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

# en cours, chercher les builds/tests
